seed: 0
optimizer: re
dataset: cifar10
out_dir: run

search:
  checkpoint_freq: 1000
  epochs: 150
  fidelity: 200

  # RE
  sample_size: 10
  population_size: 30
  
  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 100
  
  # BP
  predictor_type: feedforward
  debug_predictor: False
