
# The experiment type can be single, vary_train_size, vary_fidelity, or vary_both
# single will use train_size_single and fidleity_single 
# vary_train_size will use train_size_list and fidelity_single
# vary_fidelity will use train_size_single and fidelity_list
# vary_both will use train_size_list and fidelity_list
experiment_type: single

# nasbench101, nasbench201, darts, or nlp
search_space: nasbench201

# cifar10, cifar100, or ImageNet16-120 (only important for nasbench201)
dataset: cifar10

# one of the 31 predictors in benchmarks/predictors/runner.py
predictor: xgb

# 0: mutation-based, or 1: uniformly random, train/test sets
uniform_random: 1

# test set size
test_size: 100

# size of the training set (used by model-based predictors)
train_size_single: 50
train_size_list: [5, 8, 14, 24, 42, 71, 121, 205]

# num. epochs to train the test set arches (used by learning curve methods)
fidelity_single: 5
fidelity_list: [1, 2, 3, 5, 7, 9, 13, 19, 26, 37, 52, 73]

# output results to this directory
out_dir: run

# maximum number of seconds to run cross-validation (for model-based predictors)
max_hpo_time: 0

# random seed
seed: 1000

# these are used by the zero-cost methods
search:
  seed: 1000
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7